
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_angular_pickem_development

test:
  <<: *default
  database: rails_angular_pickem_test

production:
  <<: *default
  database: rails_angular_pickem_production
  username: rails_angular_pickem
  password: <%= ENV['RAILS_ANGULAR_PICKEM_DATABASE_PASSWORD'] %>
